config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end
  
  root 'main#home'

  get 'main/about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 5, maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "user", password: "pass", only: :destroy
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :comment)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "user", password: "pass",
  except: [:index, :show]
  
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_path
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.comment %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="menu">
  <%= link_to 'Home', controller: 'main', action: 'home' %>
  <%= link_to 'Posts', controller: 'posts' %>
  <%= link_to 'About', controller: 'main', action: 'about' %>
</div>

<%= yield %>

<div id="footer">
  <br><small>SimpleApp 2015</small>
</div>

</body>
</html>

app/views/main/about.html.erb
<h1>About</h1>
<p>This is simple Ruby on Rails application.</p>

app/views/main/home.html.erb
<h1>Home</h1>
<p>Welcome to simple Ruby on Rails application!</p>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
 
<%= link_to 'New post', new_post_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>Show Post</h1>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', posts_path %>
<%= link_to 'Edit', edit_post_path(@post) %>